<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit13f154611cc01ea9aba7ce6819677ac0
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit13f154611cc01ea9aba7ce6819677ac0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit13f154611cc01ea9aba7ce6819677ac0::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit13f154611cc01ea9aba7ce6819677ac0::$classMap;

        }, null, ClassLoader::class);
    }
}
